import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Header from '@/components/Header'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className={styles.main}>
        <h1 className="text-3xl font-bold underline dark:text-orange-600">
          Hello world!
        </h1>


      </main>

    </div>
  )
}
